### ISSUE TITLE
2기 2주차 문제 - 그리디

### ISSUE THREAD

**Issue by dustjq1004** [coding-test-java/problems#53]
### 리뷰어
- A - `상화,영우,동현`
- B - `용준,연섭,재우`
### 문제 출제자
```
재우 용준 영우
```

**Comment by jaewoopk** [comment]
난이도 실버 1, 백준 1080번 행렬 문제입니다! 혹시 푸신 분이 있다면 다른 문제 찾아보겠습니다

https://www.acmicpc.net/problem/1080

**Comment by YongGoose** [comment]
난이도 골드 4, 백준 9082번 지뢰찾기 문제입니다! 혹시 푸신 분이 있다면 알려주세요!

https://www.acmicpc.net/problem/9082

**Comment by skycloudstar-coding** [comment]
난이도 Lv2, 프로그래머스 조이스틱 관련된 문제입니다~
https://school.programmers.co.kr/learn/courses/30/lessons/42860
