### ISSUE TITLE
2기 3주차 문제, 리뷰어 - DFS/BFS

### ISSUE THREAD

**Issue by dustjq1004** [coding-test-java/problems#54]
### 리뷰어
- A - 영우, 동현, 용준
- B - 연섭, 재우, 상화

### 문제 출제자
```
연섭 동현 상화
```

**Comment by goodchoi** [comment]
프로그래머스 / lv3 / 여행경로

https://school.programmers.co.kr/learn/courses/30/lessons/43164

고득점 kit에서 선별했습니다. 푸신 분이있으시면 댓글 남겨주세요!

**Comment by idealflower-k** [comment]
백준 / 골드4 / 가장 가까운 공통 조상

https://www.acmicpc.net/problem/3584

**Comment by dustjq1004** [comment]
백준 /  실버 1 / 케빈 베이컨의 6단계 법칙
https://www.acmicpc.net/problem/1389

문제 푸신 분 있으시면 톡또는 댓글로 알려주세요!

**Comment by dustjq1004** [comment]
https://www.acmicpc.net/problem/15681
