### ISSUE TITLE
2기 4주차 문제 - 이분 탐색

### ISSUE THREAD

**Issue by dustjq1004** [coding-test-java/problems#55]
### 리뷰어
- A - 동현, 용준, 연섭
- B - 재우, 상화, 영우

### 문제 출제자
```
재우 용준 영우
```

**Comment by jaewoopk** [comment]
https://www.acmicpc.net/problem/16401

실버 2 과자나눠주기입니다! 혹시라도 푸신분 있으시면 댓글로 알려주세요!

**Comment by skycloudstar-coding** [comment]
https://www.acmicpc.net/problem/6236
실버 2 용돈관리 문제입니다! 푸신 분 계시면 이모티콘이나 댓글로 알려주세요!
