### ISSUE TITLE
2기 5주차 문제, 리뷰어 - 최단 거리

### ISSUE THREAD

**Issue by dustjq1004** [coding-test-java/problems#56]
### 리뷰어
- A - 용준, 연섭, 재우
- B - 상화, 영우, 동현

### 문제 출제자
```
연섭 동현 상화
```

**Comment by goodchoi** [comment]
[백준 - 골드 4 - 문제명 : 알고스팟](https://www.acmicpc.net/problem/1261) 
푸신분이 있으면 알려주세요~

**Comment by idealflower-k** [comment]
[백준 - 골드5 - 1916 최소비용구하기](https://www.acmicpc.net/problem/1916)

**Comment by dustjq1004** [comment]
[백준 - 골드4 - 녹색 옷 입은 애가 젤다지?](https://www.acmicpc.net/problem/4485)
