### ISSUE TITLE
3기 2주차 문제, 리뷰어 - 그리디

### ISSUE THREAD

**Issue by dustjq1004** [coding-test-java/problems#90]
### 리뷰어
A - '유성', '상화', '동현'
B - '준형', '용준', '연섭'
### 문제 출제자
```
이유성, 최동현, 이상화
```

**Comment by YuSung011017** [comment]
BOJ 2036 수열의 점수
https://www.acmicpc.net/problem/2036

**Comment by goodchoi** [comment]
BOJ 13904 과제
https://www.acmicpc.net/problem/13904

골드3 이긴한데 정답률도 괜찮고 푼 사람도 많네요 혹시 푸신분이 있으면 말씀해주세요!

**Comment by idealflower-k** [comment]
BOJ 1339 단어 수학
https://www.acmicpc.net/problem/1339
