### ISSUE TITLE
3기 4주차 문제, 리뷰어 - 백트래킹

### ISSUE THREAD

**Issue by dustjq1004** [coding-test-java/problems#92]
### 리뷰어
A - '동현', '준형', '용준'
B - '연섭', '유성', '상화'

### 문제 출제자
```
동현 유성 상화
```

**Comment by goodchoi** [comment]
[소문난 칠공주 - 골드3](https://www.acmicpc.net/problem/1941)
푸신분 있으시면 알려주세요!

**Comment by idealflower-k** [comment]
[암호 만들기 - 골드5](https://www.acmicpc.net/problem/1759)

**Comment by YuSung011017** [comment]
https://www.acmicpc.net/problem/15686 /치킨 배달/ 골드5
