### ISSUE TITLE
3기 6주차 문제, 리뷰어 - 힙

### ISSUE THREAD

**Issue by dustjq1004** [coding-test-java/problems#94]
### 문제 출제자
```
동현 상화 유성
```

**Comment by goodchoi** [comment]
https://www.acmicpc.net/problem/2109
푸신 분 있으시면 말씀해주세요!

**Comment by idealflower-k** [comment]
[골드2 - 문제집](https://www.acmicpc.net/problem/1766)

**Comment by YuSung011017** [comment]
https://school.programmers.co.kr/learn/courses/30/lessons/42626
